version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: services/bot/Dockerfile
    container_name: rt25k-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3

  dashboard:
    build:
      context: ./services/dashboard
      dockerfile: Dockerfile
    container_name: rt25k-dashboard
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./output:/app/output
